language: python
python: '3.7'
cache: pip
services:
  - postgresql
before_install:
  - 'pip install "clikit==0.3.2"'
  - 'pip install "cleo==0.7.5"'
  - 'pip install --pre "poetry==1.0.0a5"'
install:
  - 'poetry install'
before_script:
  - psql -c "CREATE ROLE acquity WITH LOGIN PASSWORD 'acquity'" -U postgres
  - psql -c 'CREATE DATABASE acquity_test;' -U postgres
script:
  - './lint.sh'
  - './test.sh'
