"""create chat room

Revision ID: 5d5a4ea37917
Revises: 28f0b17593fb
Create Date: 2019-10-18 23:17:51.276870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5a4ea37917'
down_revision = '28f0b17593fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
