"""add archive

Revision ID: 8b82e59edda1
Revises: 85b11b1c3975
Create Date: 2019-11-05 22:29:25.489080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b82e59edda1'
down_revision = '85b11b1c3975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_rooms', sa.Column('is_archived_buyer', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('chat_rooms', sa.Column('is_archived_seller', sa.Boolean(), server_default='f', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_rooms', 'is_archived_seller')
    op.drop_column('chat_rooms', 'is_archived_buyer')
    # ### end Alembic commands ###
