"""add match id

Revision ID: 8bc48fa43079
Revises: 441896589af1
Create Date: 2019-11-09 01:36:45.838980

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "8bc48fa43079"
down_revision = "441896589af1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "archived_chat_rooms",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("user_id", postgresql.UUID(), nullable=False),
        sa.Column("chat_room_id", postgresql.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["chat_room_id"], ["chat_rooms.id"]),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("chat_rooms", sa.Column("friendly_name", sa.String(), nullable=False))
    op.add_column(
        "chat_rooms", sa.Column("match_id", postgresql.UUID(), nullable=False)
    )
    op.create_foreign_key(None, "chat_rooms", "matches", ["match_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chat_rooms", type_="foreignkey")
    op.drop_column("chat_rooms", "match_id")
    op.drop_column("chat_rooms", "friendly_name")
    op.drop_table("archived_chat_rooms")
    # ### end Alembic commands ###
